# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "SeekHealing, Rethink Rehab"
excerpt_separator: <!--more-->
maps-key: "AIzaSyAWAqhAjwPii-qZQy4Qd8MjcgTl8CenG8g"
email: info@seekhealing.org
description: > # this means to ignore newlines until "baseurl:"
  It's time to rethink rehab. SeekHealing is fighting the heroin &amp; opioid
  epidemic with the only medicine that works for everyone: authentic connection.
ga_property_id: UA-96579534-1

# Build settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://seekhealing.org" # the base hostname & protocol for your site, e.g. http://example.com
permalink: "/blog/:title/"
sass:
  sass_dir: _sass
  style: compressed
include:
- _pages
exclude:
- .gitignore
- README.md
- Gemfile
- Gemfile.lock
- CNAME

# Markdown settings
markdown: kramdown
kramdown:
  auto_ids:       true
  auto_id_stripping:    true

# HTML Compression settings
compress_html:
  clippings: [ ]
  blanklines: false
  profile: false

# Jekyll Collections
# TBD AWN Review ***************************
collections:
  careers:
    title: careers
    output: true
    permalink: /careers/:path/
  exams:
    title: exams
    output: true
    permalink: /exams/:path/
  centres:
    title: centres
    output: true
    permalink: /tuition-centres/:path/
  faqs:
    title: faqs
    output: false
    permalink: /faqs/:path/
  tabular_data:
    title: tabular_data
    output: false
    permalink: /tabs/:path/
  schools:
    title: schools
    output: true
    permalink: /:path/
  team_members:
    title: team_members
    output: true
    permalink: /our-team/:path/
  tuition_services:
    title: tuition_services
    output: true
    permalink: /private-tuition/services/:path/
  tutors:
    title: tutors
    output: true
    permalink: /tutors/:path/
  what_we_teach:
    title: what_we_teach
    output: true
    permalink: /what-we-teach/:path/
  misc_sections:
    title: faqs
    output: false
    permalink: /:path/
  team_members:
    output: false

defaults:
  - scope:
      path: "/careers/"
      type: careers
    values:
      layout: subpage
  - scope:
      path: "/exams/"
      type: exams
    values:
      layout: subpage
  - scope:
      path: "/tuition-centres/"
      type: centres
    values:
      layout: subpage
  - scope:
      path: "/faqs/"
      type: faqs
    values:
      layout: subpage
  - scope:
      path: "/schools/"
      type: schools
    values:
      layout: school
  - scope:
      path: "/our-team/"
      type: team_members
    values:
      layout: our-team
  - scope:
      path: "/tabulars/"
      type: tabular_data
    values:
      layout: subpage
  - scope:
      path: "/services/"
      type: tuition_services
    values:
      layout: subpage
  - scope:
      path: "/tutors/"
      type: tutors
    values:
      layout: subpage
  - scope:
      path: "/what-we-teach/"
      type: what_we_teach
    values:
      layout: subpage
  - scope:
      path: "/misc/"
      type: misc_sections
    values:
      layout: subpage

# gems
plugins: ['jekyll-paginate', 'jekyll-sitemap', 'jekyll-last-modified-at']
paginate: 1
paginate_path: "/blog/page/:num"