backend:
  name: github
  repo: shredtechular/seekhealing.github.io
  branch: refactor
  site_domain: seekhealing-refactor.netlify.com
publish_mode: editorial_workflow
media_folder: "/assets/images"
collections:
  - name: "post" # Used in routes, e.g. /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "page" # Used in routes, e.g. /admin/collections/blog
    label: "Page" # Used in the UI
    folder: "_pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template 
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - label: "Sections"
        name: "sections"
        widget: "list"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Type", name: "type", widget: "select", options: ["connect", "hero", "locations", "single", "stories", "subnav", "subscribe"]}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "otherContent" 
    label: "Miscellaneous Content" 
    delete: false # Prevent users from deleting documents in this collection
    editor: 
      preview: false 
    files: 
      - name: "global" 
        label: "Global Site Content" 
        file: "_data/global.yaml" 
        description: "Global content" 
        fields: 
          - {label: "Email Address", name: "email", widget: "string"}
          - {label: "Email Icon", name: "email-icon", widget: "string"}
          - {label: "Subsribe Form Submission URL", name: "subscribe-url", widget: "string"}
          - {label: "Subsribe Form Text", name: "subscribe-text", widget: "string"}
          - {label: "Subsribe Form Button Text", name: "subscribe-btn-text", widget: "string"}
      - name: "header" 
        label: "Header Content" 
        file: "_data/header.yaml" 
        description: "Header content" 
        fields: 
          - label: "Logo Image"
            name: "logo"
            widget: "image"
          - {label: "Logo Alt Text", name: "logo-alt", widget: "string"}
          - label: "Header Navigation Items" 
            name: nav 
            widget: "list" 
            fields: 
              - {label: "Title", name: title, widget: string}
              - {label: "URL", name: url, widget: string}
              - label: "Target"
                name: target
                widget: select
                options: ["", "_blank"]
              - label: "SubMenu"
                name: submenu
                widget: list
                fields:
                  - {label: "Title", name: title, widget: string}
                  - {label: "URL", name: url, widget: string}
                  - label: "Target"
                    name: target
                    widget: select
                    options: ["", "_blank"]
      - name: "footer" 
        label: "Footer Content" 
        file: "_data/footer.yaml" 
        description: "Footer content" 
        fields: 
          - {label: "Copyright Text", name: "copyright-text", widget: "string"}
          - label: "Footer Navigation Items" 
            name: nav 
            widget: "list" 
            fields: 
              - {label: "Title", name: title, widget: string}
              - {label: "URL", name: url, widget: string}
              - label: "Target"
                name: target
                widget: select
                options: ["", "_blank"]
          - label: "Footer Social Media Links" 
            name: "social-media"
            widget: "list"
            fields: 
              - {label: "Icon class", name: icon, widget: string}
              - {label: "URL", name: url, widget: string}
      - name: "contact" 
        label: "Contact Page Content" 
        file: "_data/contact.yaml" 
        description: "Contact Page content" 
        fields: 
          - {label: "Contact Header", name: "location-header", widget: "string"}
          - label: "Location Contacts" 
            name: location-contacts 
            widget: "list"
            fields:
              - {label: "City", name: city, widget: string}
              - {label: "State", name: state, widget: string}
              - {label: "Contact Email Address", name: email, widget: string}
          - {label: "Connect Header", name: "connect-header", widget: "string"}